version: '3.9'
services:
    api:
        image: go-rest-api
        build: .
        environment:
            testenv: tejas-test
        ports:
            - 8080:8080
        depends_on:
            - database

    database:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: badpassword
        ports:
            - 27017:27017
        volumes:
              - order_data_container:/data/db
        
volumes:
  order_data_container: